name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Cambia a la rama que quieras usar para el deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public # Carpeta de salida (./public)
